name: Frontend - Deploy

on:
  push:
    branches:
    - master

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build App
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: yarn install
    - run: yarn build
    - name: Upload dist folder
      uses: actions/upload-artifact@v3
      with:
        name: dist folder
        path: frontend/dist
  test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Unit and E2E
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: yarn install
    - run: yarn test
    - run: yarn e2e --headless --watch=false
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - name: Download dist folder
      uses: actions/download-artifact@v3
      with:
        name: dist folder
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Deploy
      run: aws s3 sync . s3://locallibrary-rjnay