name: Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: use Node.js 16.x
    - uses: actions/setup-node@v2
      with: 
        node-version: 16.x
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test --ci --run-in-band
    - run: yarn lint